<?xml version="1.0"?>
<package format="3">
  <name>turtlebot3_inspection_bringup</name>
  <version>0.1.0</version>
  <description>Launch files, maps, and configuration for the TurtleBot3 inspection project.</description>
  <maintainer email="robotics@example.com">Robotics Team 1</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>sound_anomaly</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>turtlebot3_bringup</exec_depend>
  <exec_depend>turtlebot3_navigation2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
